### ISSUE TITLE
Добавление возможности QR

### ISSUE THREAD

**Issue by AlexKatyukov** [SPEEDCUBES-TECH/tnoodle-barcode-pdf#1]
Такие ШК фактически довольно хреново читаются с мобилки 2д сканнером с Озона.
Мб разрешить выбирать формат — такие коды (для всяких 1д считывалок) или QR коды (с экрана мобилки 2д считывателями они читаются лучше)

**Comment by ThaEin** [comment]
Я правильно понимаю что подразумевается такое?
| mobile  | print |
| ----------- | ------- |
| ![example mobile png-16](https://github.com/SPEEDCUBES-TECH/tnoodle-barcode-pdf/assets/16339036/3cc4de3e-9242-4d90-808f-0d4b094ada24) | ![example print png-04](https://github.com/SPEEDCUBES-TECH/tnoodle-barcode-pdf/assets/16339036/39967fde-c27f-417b-82da-027c8cdd01c1) |

- [example.mobile.pdf](https://github.com/SPEEDCUBES-TECH/tnoodle-barcode-pdf/files/12773353/example.mobile.pdf)
- [example.print.pdf](https://github.com/SPEEDCUBES-TECH/tnoodle-barcode-pdf/files/12773355/example.print.pdf)

**Comment by ThaEin** [comment]
Будем считать что да. [Версия с QR кодами](https://github.com/SPEEDCUBES-TECH/tnoodle-barcode-pdf/releases/tag/v1.3.0)
